// Code generated by modernc.org/undup from the per-target vec_*.go files; DO NOT EDIT.

//go:build (darwin && amd64) || (darwin && arm64) || (openbsd && amd64) || (openbsd && arm64)

package vec

import (
	"modernc.org/libc"
)

type Tdev_t = int32

type Tregister_t = int64

func _distance_hamming_u64(tls *libc.TLS, a uintptr, b uintptr, n Tsize_t) (r Tf32) {
	var i uint64
	var same int32
	_, _ = i, same
	same = 0
	i = uint64(0)
	for {
		if !(i < n) {
			break
		}
		same = same + libc.X__builtin_popcountl(tls, uint64(**(**Tu64)(__ccgo_up(a + uintptr(i)*8))^**(**Tu64)(__ccgo_up(b + uintptr(i)*8))))
		goto _1
	_1:
		;
		i = i + 1
	}
	return float32(same)
}

const m___INT64_C_SUFFIX__ = "LL"

const m___INT64_FMTd__ = "lld"

const m___INT64_FMTi__ = "lli"

const m___STDC_NO_THREADS__ = 1

const m___UINT64_C_SUFFIX__ = "ULL"

const m___UINT64_FMTX__ = "llX"

const m___UINT64_FMTo__ = "llo"

const m___UINT64_FMTu__ = "llu"

const m___UINT64_FMTx__ = "llx"

const m___UINT64_MAX__ = "18446744073709551615U"

type register_t = Tregister_t
