// Code generated by modernc.org/undup from the per-target vec_*.go files; DO NOT EDIT.

//go:build (linux && 386) || (linux && amd64) || (linux && arm) || (linux && arm64) || (linux && s390x) || (windows && (amd64 || arm64)) || (windows && 386)

package vec

const m___GNUC__ = 12

const m___GXX_ABI_VERSION = 1017
