// Code generated by modernc.org/undup from the per-target vec_*.go files; DO NOT EDIT.

//go:build (freebsd && 386) || (freebsd && amd64) || (freebsd && arm) || (freebsd && arm64) || (linux && 386) || (linux && amd64) || (linux && arm) || (linux && arm64) || (linux && loong64) || (linux && ppc64le) || (linux && riscv64) || (linux && s390x) || (netbsd && amd64) || (openbsd && amd64) || (openbsd && arm64)

package vec

type Tint_fast16_t = int32

type Tlocale_t = uintptr

type Tuint_fast16_t = uint32

type locale_t = Tlocale_t

const m_SCNdFAST16 = "d"

const m_SCNiFAST16 = "i"

const m_SCNoFAST16 = "o"

const m_SCNuFAST16 = "u"

const m_SCNxFAST16 = "x"

const m___ELF__ = 1

const m___unix__ = 1
