// Code generated by modernc.org/undup from the per-target vec_*.go files; DO NOT EDIT.

//go:build (freebsd && 386) || (freebsd && amd64) || (freebsd && arm) || (freebsd && arm64) || (linux && 386) || (linux && amd64) || (linux && arm) || (linux && arm64) || (linux && loong64) || (linux && ppc64le) || (linux && riscv64) || (linux && s390x) || (openbsd && amd64) || (openbsd && arm64)

package vec

const m_INT16_MAX = 0x7fff

const m_INT32_MAX = 0x7fffffff

const m_INT64_MAX = 0x7fffffffffffffff

const m_UINT16_MAX = 0xffff

const m_UINT8_MAX = 0xff

const m___unix = 1
