// Code generated by modernc.org/undup from the per-target vec_*.go files; DO NOT EDIT.

//go:build (darwin && amd64) || (darwin && arm64) || (freebsd && 386) || (freebsd && amd64) || (freebsd && arm) || (freebsd && arm64) || (linux && 386) || (linux && amd64) || (linux && arm) || (linux && arm64) || (linux && loong64) || (linux && ppc64le) || (linux && riscv64) || (linux && s390x) || (openbsd && amd64) || (openbsd && arm64)

package vec

const m_NAME_MAX = 255

const m__POSIX_CLOCKRES_MIN = 20000000

const m__POSIX_SEM_VALUE_MAX = 32767

const m__XOPEN_NAME_MAX = 255
