// Code generated by modernc.org/undup from the per-target vec_*.go files; DO NOT EDIT.

//go:build (freebsd && amd64) || (freebsd && arm64) || (openbsd && amd64) || (openbsd && arm64)

package vec

const m_FP_INFINITE = 0x01

const m_FP_NAN = 0x02

const m_FP_NORMAL = 0x04

const m_FP_SUBNORMAL = 0x08

const m_FP_ZERO = 0x10

const m_GID_MAX = "UINT_MAX"

const m_M_1_PIl = 0.318309886183790671537767526745028724

const m_M_2_PIl = 0.636619772367581343075535053490057448

const m_M_2_SQRTPIl = 1.128379167095512573896158903121545172

const m_M_El = 2.718281828459045235360287471352662498

const m_M_LN10l = 2.302585092994045684017991454684364208

const m_M_LN2l = 0.693147180559945309417232121458176568

const m_M_LOG10El = 0.434294481903251827651128918916605082

const m_M_LOG2El = 1.442695040888963407359924681001892137

const m_M_PI_2l = 1.570796326794896619231321691639751442

const m_M_PI_4l = 0.785398163397448309615660845819875721

const m_M_PIl = 3.141592653589793238462643383279502884

const m_M_SQRT1_2l = 0.707106781186547524400844362104849039

const m_M_SQRT2l = 1.414213562373095048801688724209698079

const m_OPEN_MAX = 64

const m_PRIXMAX = "jX"

const m_PRIdMAX = "jd"

const m_PRIiMAX = "ji"

const m_PRIoMAX = "jo"

const m_PRIuMAX = "ju"

const m_PRIxMAX = "jx"

const m_SCNdMAX = "jd"

const m_SCNiMAX = "ji"

const m_SCNoMAX = "jo"

const m_SCNuMAX = "ju"

const m_SCNxMAX = "jx"

const m_UID_MAX = "UINT_MAX"

const m_WINT_MAX = "INT32_MAX"

const m_WINT_MIN = "INT32_MIN"

const m___BOOL_WIDTH__ = 8

const m___BSD_VISIBLE = 1

const m___INT_FAST64_FMTd__ = "ld"

const m___INT_FAST64_FMTi__ = "li"

const m___INT_LEAST64_FMTd__ = "ld"

const m___INT_LEAST64_FMTi__ = "li"

const m___POSIX_VISIBLE = 202405

const m___UINT_FAST64_FMTX__ = "lX"

const m___UINT_FAST64_FMTo__ = "lo"

const m___UINT_FAST64_FMTu__ = "lu"

const m___UINT_FAST64_FMTx__ = "lx"

const m___UINT_FAST64_MAX__ = 18446744073709551615

const m___UINT_LEAST64_FMTX__ = "lX"

const m___UINT_LEAST64_FMTo__ = "lo"

const m___UINT_LEAST64_FMTu__ = "lu"

const m___UINT_LEAST64_FMTx__ = "lx"

const m___UINT_LEAST64_MAX__ = 18446744073709551615

const m___clang_major__ = 19

const m___clang_minor__ = 1

const m___clang_patchlevel__ = 7

type t__blkcnt_t = int64

type t__blksize_t = int32

type t__clockid_t = int32

type t__double_t = float64

type t__fixpt_t = uint32

type t__float_t = float32

type t__ino_t = uint64

type t__int_fast16_t = int32

type t__int_fast32_t = int32

type t__int_fast64_t = int64

type t__int_fast8_t = int32

type t__int_least16_t = int16

type t__int_least32_t = int32

type t__int_least64_t = int64

type t__int_least8_t = int8

type t__intmax_t = int64

type t__key_t = int64

type t__ptrdiff_t = int64

type t__rune_t = int32

type t__size_t = uint64

type t__ssize_t = int64

type t__suseconds_t = int64

type t__time_t = int64

type t__uint_fast16_t = uint32

type t__uint_fast32_t = uint32

type t__uint_fast64_t = uint64

type t__uint_fast8_t = uint32

type t__uint_least16_t = uint16

type t__uint_least32_t = uint32

type t__uint_least64_t = uint64

type t__uint_least8_t = uint8

type t__uintmax_t = uint64

type t__useconds_t = uint32

type t__wint_t = int32
