// Code generated by modernc.org/undup from the per-target vec_*.go files; DO NOT EDIT.

//go:build (darwin && amd64) || (darwin && arm64) || (freebsd && 386) || (freebsd && amd64) || (freebsd && arm) || (freebsd && arm64) || (linux && 386) || (linux && amd64) || (linux && arm) || (linux && arm64) || (linux && loong64) || (linux && ppc64le) || (linux && riscv64) || (linux && s390x)

package vec

const m_BC_BASE_MAX = 99

const m_BC_DIM_MAX = 2048

const m_BC_SCALE_MAX = 99

const m_BC_STRING_MAX = 1000

const m__POSIX_RTSIG_MAX = 8

const m__POSIX_SS_REPL_MAX = 4

const m__POSIX_TRACE_EVENT_NAME_MAX = 30

const m__POSIX_TRACE_NAME_MAX = 8

const m__POSIX_TRACE_SYS_MAX = 8

const m__POSIX_TRACE_USER_EVENT_MAX = 32
