// Code generated by modernc.org/undup from the per-target vec_*.go files; DO NOT EDIT.

//go:build (darwin && amd64) || (freebsd && amd64) || (freebsd && arm64) || (openbsd && amd64) || (openbsd && arm64)

package vec

const m___OBJC_BOOL_IS_BOOL = 0
