// Code generated by modernc.org/undup from the per-target vec_*.go files; DO NOT EDIT.

//go:build (darwin && amd64) || (darwin && arm64) || (linux && riscv64)

package vec

const m__FORTIFY_SOURCE = 2
