// Code generated by modernc.org/undup from the per-target vec_*.go files; DO NOT EDIT.

//go:build (linux && arm) || (linux && riscv64)

package vec

const m___GCC_ATOMIC_BOOL_LOCK_FREE = 1

const m___GCC_ATOMIC_CHAR16_T_LOCK_FREE = 1

const m___GCC_ATOMIC_CHAR_LOCK_FREE = 1

const m___GCC_ATOMIC_SHORT_LOCK_FREE = 1
