// Code generated by modernc.org/undup from the per-target vec_*.go files; DO NOT EDIT.

//go:build (darwin && arm64) || (linux && arm) || (linux && s390x)

package vec

const m___BIGGEST_ALIGNMENT__ = 8
