// Code generated by modernc.org/undup from the per-target sqlite_*.go files; DO NOT EDIT.

package sqlite3

import (
	"modernc.org/libc"
)

type Sqlite3_index_info = sqlite3_index_info

type Sqlite3_module = sqlite3_module

type Sqlite3_vtab_cursor = sqlite3_vtab_cursor

func Xsqlite3_soft_heap_limit(tls *libc.TLS, n int32) {
	if n < 0 {
		n = 0
	}
	Xsqlite3_soft_heap_limit64(tls, int64(n))
}
