// Code generated by modernc.org/undup from the per-target sqlite_*.go files; DO NOT EDIT.

//go:build (darwin && arm64) || (linux && arm) || (linux && s390x)

package sqlite3

const __BIGGEST_ALIGNMENT__ = 8
