// Code generated by modernc.org/undup from the per-target sqlite_*.go files; DO NOT EDIT.

//go:build (freebsd && amd64) || (freebsd && arm64) || (linux && amd64) || (linux && ppc64le) || (linux && s390x)

package sqlite3

type Tnlink_t = uint64
