// Code generated by modernc.org/undup from the per-target sqlite_*.go files; DO NOT EDIT.

//go:build (darwin && amd64) || (darwin && arm64) || (netbsd && amd64)

package sqlite3

import (
	"modernc.org/libc"
)

const CHARCLASS_NAME_MAX = 14

const COLL_WEIGHTS_MAX = 2

const ENOATTR = 93

const EXPR_NEST_MAX = 32

const FP_NAN = 1

const GID_MAX = 2147483647

const LINE_MAX = 2048

const LINK_MAX = 32767

const MAP_NORESERVE = 64

const MAP_RENAME = 32

const NGROUPS_MAX = 16

const NZERO = 20

const PATH_MAX = 1024

const PIPE_BUF = 512

const RE_DUP_MAX = 255

const TIOCGSIZE = "TIOCGWINSZ"

const TIOCSSIZE = "TIOCSWINSZ"

type Texception = struct {
	Ftype1  int32
	Fname   uintptr
	Farg1   float64
	Farg2   float64
	Fretval float64
}

type Tidtype_t = int32

type Tkauth_cred_t = uintptr

type Tsuseconds_t = int32

type Tswblk_t = int32

type Tttysize = struct {
	Fts_lines uint16
	Fts_cols  uint16
	Fts_xxx   uint16
	Fts_yyy   uint16
}

const UID_MAX = 2147483647

const X_TLOSS = 0

const _POSIX2_VERSION = 200112

const _POSIX_THREAD_KEYS_MAX = 128

const _POSIX_VERSION = 200112

const _P_ALL = 0

const _P_PID = 1

// C documentation
//
//	/*
//	** Find the current time (in Universal Coordinated Time).  Write into *piNow
//	** the current time and date as a Julian Day number times 86_400_000.  In
//	** other words, write into *piNow the number of milliseconds since the Julian
//	** epoch of noon in Greenwich on November 24, 4714 B.C according to the
//	** proleptic Gregorian calendar.
//	**
//	** On success, return SQLITE_OK.  Return SQLITE_ERROR if the time and date
//	** cannot be found.
//	*/
func _unixCurrentTimeInt64(tls *libc.TLS, NotUsed uintptr, piNow uintptr) (r int32) {
	bp := tls.Alloc(16)
	defer tls.Free(16)
	var rc int32
	var _ /* sNow at bp+0 */ Ttimeval
	_ = rc
	rc = SQLITE_OK
	libc.Xgettimeofday(tls, bp, uintptr(0)) /* Cannot fail given valid arguments */
	**(**Tsqlite3_int64)(__ccgo_up(piNow)) = _unixEpoch + int64(1000)*int64((**(**Ttimeval)(__ccgo_up(bp))).Ftv_sec) + int64((**(**Ttimeval)(__ccgo_up(bp))).Ftv_usec/int32(1000))
	_ = NotUsed
	return rc
}

type exception = Texception

type idtype_t = Tidtype_t

type kauth_cred_t = Tkauth_cred_t

type stack_t = Tstack_t

type swblk_t = Tswblk_t

type t__sFILE = TFILE

type ttysize = Tttysize
