// Copyright 2026 The Sqlite Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package vendorstamp

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// The stamp committed with this repository must describe the lib/ and vec/
// committed with it.
func TestRepositoryStamp(t *testing.T) {
	if err := Check(filepath.Join("..", "..")); err != nil {
		t.Fatal(err)
	}
}

const (
	libCommit = "d8e6f786be2487508b613b2455674e07e84a4ed9"
	vecCommit = "3de939e04a82c22c5446ca556f6858a911767dee"
)

// fixture writes a small repository whose stamp passes Check, after edit has
// changed the stamp, and returns its root.
func fixture(t *testing.T, edit func(m map[string]any)) string {
	t.Helper()
	root := t.TempDir()
	files := map[string]string{
		"go.mod":             "module modernc.org/sqlite\n\ngo 1.25.0\n\nrequire (\n\tmodernc.org/libc v1.75.7 // pinned\n\tmodernc.org/mathutil v1.7.1\n)\n",
		"lib/sqlite.go":      "// Code generated by modernc.org/undup; DO NOT EDIT.\n\npackage sqlite3\n",
		"lib/sqlite_a_b.go":  "// Code generated for a/b; DO NOT EDIT.\n\npackage sqlite3\n",
		"lib/defs.go":        "package sqlite3 // hand-written, not output\n",
		"vec/vec.go":         "// Code generated by modernc.org/undup; DO NOT EDIT.\n\npackage vec\n",
		"vec/patches.go":     "package vec // hand-written, not output\n",
		"LICENSE-SQLITE_VEC": "MIT\n",
	}
	for name, content := range files {
		p := filepath.Join(root, filepath.FromSlash(name))
		if err := os.MkdirAll(filepath.Dir(p), 0755); err != nil {
			t.Fatal(err)
		}

		if err := os.WriteFile(p, []byte(content), 0644); err != nil {
			t.Fatal(err)
		}
	}

	n, sum, err := OutputDigest(root)
	if err != nil {
		t.Fatal(err)
	}

	if n != 4 {
		t.Fatalf("fixture has %d output files, want 4", n)
	}

	m := map[string]any{
		"go":    "go1.27.1",
		"undup": "modernc.org/undup@v0.0.5",
		"sources": []any{
			map[string]any{
				"module": "modernc.org/libsqlite3", "into": "lib", "commit": libCommit,
				"tags": []any{"v1.14.5"}, "dirty": false,
				"requires": map[string]any{"modernc.org/ccgo/v4": "v4.35.0", "modernc.org/libc": "v1.75.7"},
			},
			map[string]any{
				"module": "modernc.org/libsqlite_vec", "into": "vec", "commit": vecCommit,
				"tags": []any{"v0.5.0"}, "dirty": false,
				"requires": map[string]any{"modernc.org/ccgo/v4": "v4.35.2", "modernc.org/libc": "v1.75.7", "modernc.org/libsqlite3": "v1.14.5"},
			},
		},
		"output": map[string]any{"files": n, "sha256": sum},
	}
	if edit != nil {
		edit(m)
	}

	b, err := json.MarshalIndent(m, "", "  ")
	if err != nil {
		t.Fatal(err)
	}

	if err := os.WriteFile(filepath.Join(root, FileName), append(b, '\n'), 0644); err != nil {
		t.Fatal(err)
	}

	return root
}

func source(m map[string]any, i int) map[string]any {
	return m["sources"].([]any)[i].(map[string]any)
}

func requires(m map[string]any, i int) map[string]any {
	return source(m, i)["requires"].(map[string]any)
}

func TestCheckAccepts(t *testing.T) {
	for _, tc := range []struct {
		name string
		edit func(m map[string]any)
	}{
		{"as written", nil},
		// vec may name libsqlite3 by any tag of the commit lib/ came from
		{"one of several tags", func(m map[string]any) { source(m, 0)["tags"] = []any{"v1.14.5", "v1.15.0"} }},
		// or by a pseudo-version, which ends in a prefix of that commit
		{"pseudo-version", func(m map[string]any) {
			source(m, 0)["tags"] = []any{}
			requires(m, 1)["modernc.org/libsqlite3"] = "v1.14.6-0.20260914182010-" + libCommit[:12]
		}},
		{"pseudo-version on a prerelease", func(m map[string]any) {
			source(m, 0)["tags"] = []any{}
			requires(m, 1)["modernc.org/libsqlite3"] = "v1.14.6-rc.1.0.20260914182010-" + libCommit[:12]
		}},
		{"pseudo-version without a base", func(m map[string]any) {
			source(m, 0)["tags"] = []any{}
			requires(m, 1)["modernc.org/libsqlite3"] = "v0.0.0-20260914182010-" + libCommit[:12]
		}},
	} {
		t.Run(tc.name, func(t *testing.T) {
			if err := Check(fixture(t, tc.edit)); err != nil {
				t.Fatal(err)
			}
		})
	}
}

func TestCheckRefuses(t *testing.T) {
	for _, tc := range []struct {
		name string
		edit func(m map[string]any)
		want string
	}{
		{"dirty", func(m map[string]any) { source(m, 1)["dirty"] = true }, "uncommitted changes"},
		{"dirty missing", func(m map[string]any) { delete(source(m, 0), "dirty") }, "dirty is missing"},
		{"dirty null", func(m map[string]any) { source(m, 0)["dirty"] = nil }, "dirty is missing"},
		{"libc differs between sources", func(m map[string]any) { requires(m, 1)["modernc.org/libc"] = "v1.75.6" }, "must be the same"},
		{"libc differs from go.mod", func(m map[string]any) {
			requires(m, 0)["modernc.org/libc"] = "v1.75.8"
			requires(m, 1)["modernc.org/libc"] = "v1.75.8"
		}, "go.mod requires v1.75.7"},
		{"libc missing", func(m map[string]any) { delete(requires(m, 0), "modernc.org/libc") }, "no modernc.org/libc"},
		{"vec built against another libsqlite3", func(m map[string]any) { requires(m, 1)["modernc.org/libsqlite3"] = "v1.14.4" }, "vec/ requires modernc.org/libsqlite3 v1.14.4"},
		{"lib untagged", func(m map[string]any) { source(m, 0)["tags"] = []any{} }, "vec/ requires modernc.org/libsqlite3 v1.14.5"},
		{"pseudo-version of another commit", func(m map[string]any) {
			requires(m, 1)["modernc.org/libsqlite3"] = "v1.14.6-0.20260914182010-" + vecCommit[:12]
		}, "but lib/ came from commit"},
		{"libsqlite3 requirement missing", func(m map[string]any) { delete(requires(m, 1), "modernc.org/libsqlite3") }, "no modernc.org/libsqlite3"},
		{"sources swapped", func(m map[string]any) {
			s := m["sources"].([]any)
			s[0], s[1] = s[1], s[0]
		}, "want modernc.org/libsqlite3 into lib"},
		{"a source missing", func(m map[string]any) { m["sources"] = m["sources"].([]any)[:1] }, "1 sources, want 2"},
		{"short commit", func(m map[string]any) { source(m, 0)["commit"] = libCommit[:12] }, "not a full hash"},
		{"unknown field", func(m map[string]any) { m["extra"] = 1 }, "unknown field"},
		{"no toolchain", func(m map[string]any) { m["go"] = "" }, "not a Go toolchain"},
		{"no undup pin", func(m map[string]any) { m["undup"] = "modernc.org/undup" }, "not pkg@version"},
		{"stale digest", func(m map[string]any) {
			m["output"].(map[string]any)["sha256"] = strings.Repeat("0", 64)
		}, "must not be edited by hand"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			err := Check(fixture(t, tc.edit))
			if err == nil || !strings.Contains(err.Error(), tc.want) {
				t.Fatalf("got %v, want an error containing %q", err, tc.want)
			}
		})
	}
}

// Editing, adding or removing an output file after the stamp was written is
// caught; hand-written files next to them, and line-ending conversion, are not
// the stamp's business.
func TestCheckOutput(t *testing.T) {
	for _, tc := range []struct {
		name   string
		change func(root string) error
		ok     bool
	}{
		{"generated file edited", func(root string) error {
			return os.WriteFile(filepath.Join(root, "lib", "sqlite_a_b.go"), []byte("// Code generated for a/b; DO NOT EDIT.\n\npackage sqlite3 // edited\n"), 0644)
		}, false},
		{"generated file added", func(root string) error {
			return os.WriteFile(filepath.Join(root, "vec", "vec_c_d.go"), []byte("package vec\n"), 0644)
		}, false},
		{"generated file removed", func(root string) error {
			return os.Remove(filepath.Join(root, "lib", "sqlite_a_b.go"))
		}, false},
		{"notice edited", func(root string) error {
			return os.WriteFile(filepath.Join(root, "LICENSE-SQLITE_VEC"), []byte("MIT, edited\n"), 0644)
		}, false},
		{"hand-written file edited", func(root string) error {
			return os.WriteFile(filepath.Join(root, "lib", "defs.go"), []byte("package sqlite3 // edited\n"), 0644)
		}, true},
		{"line endings converted", func(root string) error {
			p := filepath.Join(root, "vec", "vec.go")
			b, err := os.ReadFile(p)
			if err != nil {
				return err
			}

			return os.WriteFile(p, []byte(strings.ReplaceAll(string(b), "\n", "\r\n")), 0644)
		}, true},
	} {
		t.Run(tc.name, func(t *testing.T) {
			root := fixture(t, nil)
			if err := tc.change(root); err != nil {
				t.Fatal(err)
			}

			err := Check(root)
			switch {
			case tc.ok && err != nil:
				t.Fatal(err)
			case !tc.ok && (err == nil || !strings.Contains(err.Error(), "must not be edited by hand")):
				t.Fatalf("got %v, want the output mismatch", err)
			}
		})
	}
}

func TestGoModRequire(t *testing.T) {
	p := filepath.Join(t.TempDir(), "go.mod")
	content := "module x\n\nrequire modernc.org/single v1.0.0\n\nrequire (\n\tmodernc.org/libc v1.75.7 // indirect\n\t// modernc.org/commented v9.9.9\n)\n"
	if err := os.WriteFile(p, []byte(content), 0644); err != nil {
		t.Fatal(err)
	}

	for path, want := range map[string]string{
		"modernc.org/single":    "v1.0.0",
		"modernc.org/libc":      "v1.75.7",
		"modernc.org/commented": "",
		"modernc.org/absent":    "",
	} {
		got, err := GoModRequire(p, path)
		if err != nil || got != want {
			t.Errorf("%s: got %q, %v, want %q", path, got, err, want)
		}
	}
}

// Anything after the object makes the stamp invalid, including closing
// brackets that a decoder looking for more elements would not notice.
func TestCheckTrailingData(t *testing.T) {
	for _, tail := range []string{"{}", "]", "} garbage", "\"x\""} {
		root := fixture(t, nil)
		p := filepath.Join(root, FileName)
		b, err := os.ReadFile(p)
		if err != nil {
			t.Fatal(err)
		}

		if err := os.WriteFile(p, append(b, tail...), 0644); err != nil {
			t.Fatal(err)
		}

		if err := Check(root); err == nil || !strings.Contains(err.Error(), "after the JSON object") {
			t.Errorf("tail %q: got %v, want the trailing data refused", tail, err)
		}
	}
}

func TestGoModRequireSyntax(t *testing.T) {
	for _, tc := range []struct {
		name, content, want string
		fails               bool
	}{
		{"quoted path and version", "module \"x\"\n\nrequire \"modernc.org/libc\" \"v1.75.7\"\n", "v1.75.7", false},
		{"block opened without a space", "module x\n\nrequire(\n\tmodernc.org/libc v1.75.7\n)\n", "v1.75.7", false},
		{"required twice", "module x\n\nrequire modernc.org/libc v1.75.8\n\nrequire (\n\tmodernc.org/libc v1.75.7\n)\n", "", true},
	} {
		t.Run(tc.name, func(t *testing.T) {
			p := filepath.Join(t.TempDir(), "go.mod")
			if err := os.WriteFile(p, []byte(tc.content), 0644); err != nil {
				t.Fatal(err)
			}

			got, err := GoModRequire(p, "modernc.org/libc")
			if tc.fails != (err != nil) || got != tc.want {
				t.Fatalf("got %q, %v, want %q, error %v", got, err, tc.want, tc.fails)
			}
		})
	}
}
